In [2]:
#Consider the below code to answer further questions:


import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

In [ ]:
#There is difference bnetween these 2 types

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(array_list)

numpy.ndarray

In [6]:
type(list_)

list

Q2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [17]:
list(type(i) for i in list_)

[str, str, str, str, str]

In [18]:
list(type(i) for i in array_list)

[numpy.str_, numpy.str_, numpy.str_, numpy.str_, numpy.str_]

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [ ]:
#array_list shows type of elements as int and list_ shows the type of element as string

In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
array_list

array([1, 2, 3, 4, 5])

In [21]:
list(type(i) for i in array_list)

[numpy.int64, numpy.int64, numpy.int64, numpy.int64, numpy.int64]

In [23]:
list(type(i) for i in list_)

[str, str, str, str, str]

In [24]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [25]:
num_array.shape

(2, 3)

In [26]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [34]:
import numpy as np
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
a.shape

(3, 3)

In [36]:
a.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [39]:
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])